GET http://localhost:8080/api/clubRequest/all
###
GET http://localhost:8080/api/clubRequest/1
###
GET http://localhost:8080/api/clubRequest/club/1
###
GET http://localhost:8080/api/clubRequest/user/5
###
GET http://localhost:8080/api/clubRequest/name/subclubname


