GET http://localhost:8080/api/memberships
Accept: application/json

###

GET http://localhost:8080/api/membership/user/2
Accept: application/json

###

GET http://localhost:8080/api/membership/subclub/2
Accept: application/json