PUT http://localhost:8080/api/user/about
Content-Type: application/json

{
  "id": 2,
  "about": "user 2 update about 2"
}

###

PUT http://localhost:8080/api/user/makeadmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxNGFkbWluIiwiaWF0IjoxNjI0NTM2MDEwLCJleHAiOjE2MjQ3NTIwMTB9.MjBiiePJz7CvhsQz28oAJ5UbGK2neiiDUTNiQoGI23o

{
  "id": 2
}

###

PUT http://localhost:8080/api/user/revokeadmin
Content-Type: application/json

{
  "id": 4
}